export * from './User/Home'
export * from './User/Register'
export * from './User/PhimDetail'
export * from './User/Login'

export * from './Admin/AddFilm'
export * from './Admin/AdminFilm'
export * from './Admin/AddUser'
export * from './Admin/ShowTime'
export * from './Admin/AdminUser'